name: build-flask-app

on:
  workflow_dispatch
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]

env:
  BASE_IMAGE_REPO: tsmacrquarantineusw2.azurecr.io/toddysm/python
  BASE_IMAGE_TAG: ${{ vars.BASE_IMAGE_TAG }}
  BASE_IMAGE_DIGEST: ${{ vars.BASE_IMAGE_DIGEST }}
  NOTATION_EXPERIMENTAL: 1

jobs:
  verify-base-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Display environment
        run: |
          echo "BASE_IMAGE_REPO: $BASE_IMAGE_REPO"
          echo "BASE_IMAGE_TAG: $BASE_IMAGE_TAG"
          echo "BASE_IMAGE_DIGEST: $BASE_IMAGE_DIGEST"
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Notation CLI
        uses: notaryproject/notation-action/setup@v1
        with:
          version: "1.0.0"
      - name: Verify Base Image Signature
        uses: notaryproject/notation-action/verify@v1
        with:
          target_artifact_reference: ${{ env.BASE_IMAGE_REPO }}:{{ env.BASE_IMAGE_TAG }}
          trust_policy: .github/trustpolicy/build-stage/trustpolicy.json
          trust_store: .github/truststore
          allow_referrers_api: 'true'
